# Generated by Django 6.0 on 2026-01-22 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bus_app", "0002_booking_hold_expires_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="booking",
            name="unique_seat_per_trip",
        ),
    ]
