# Generated by Django 6.0 on 2026-01-22 06:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_app", "0003_alter_booking_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_cancelled", False)),
                fields=("trip", "seat_number"),
                name="unique_active_seat_per_trip",
            ),
        ),
    ]
